### PR TITLE
Make firefox problems go away

### PR DESCRIPTION
**Pull request by tbodt**
Fixed two, including the one that (afaik) got the addon taken down from AMO.

### CODE REVIEW

**Comment by dimdenGD** [comment]
I don't understand what this PR does. Looks like just restructured code to me. Extension was taken down for using eval, you can't really fix that.

**Comment by tbodt** [comment]
First commit removes the content_security_policy from the manifest. Now the challenge code is evaluated in the context of twitter.com and not the extension. That was the issue, right?

Second commit resolves the bug where enhanced tracking protection made the fetch for the challenge fail, which I didn't know about for a long time because that was just timing out and then using unsigned requests, until I git pulled the repo to work on this and got the `alert()` about unsigned requests no longer being allowed. Just making the fetch in the twitter.com context fixes this.

**Comment by tbodt** [comment]
Like, the sandbox.html was a very ineffective sandbox - it had full access to extension APIs with the permission of the extension, and twitter could have pushed code which would remotely execute with the permission of the extension. No longer possible when loading the sandbox from the origin of a twitter blob url, it would now just run with the permission of twitter.com as was designed.

**Comment by dimdenGD** [comment]
Hm, I didn't know you can use object urls for iframes. I don't know if it'll pass AMO's review, but it's a worth a try, thanks!

**Comment by dimdenGD** [comment]
Also, Chrome version is using built-in sandbox feature in manifest, so it can't access any APIs

**Comment by tbodt** [comment]
Oh didn't know that. I guess the issue is firefox doesn't support the sandbox mode

**Pull request merged**
