### PR TITLE
feat: improve "this user does not exist" page

### PR DESCRIPTION
**Pull request by not-nullptr**
my changes add a new "user does not exist" page. i have only updated the english localisation as its the only language i speak (sorry). here's a screenshot:3

image

### CODE REVIEW

**Comment by not-nullptr** [comment]
oh btw sorry for not putting this here, i saw other contributors putting it in so !! my handle is @notnullptr if u deem this contribution enough ^-^

**Comment by dimdenGD** [comment]
Probably should hide profile picture or set it to default image

**Comment by not-nullptr** [comment]
good call, was messing around with the whole pfp/banner area for a while. i did set the banner to the default as a test but it felt like the user did exist at first glance. here's how it looks w/ default pfp :3
image

**Comment by not-nullptr** [comment]
here it is w/ no pfp, i personally prefer the default one
image

**Comment by dimdenGD** [comment]
im fine with default

**Comment by not-nullptr** [comment]
all done !

**Pull request merged**
