### PR TITLE
minor translation fixes in pt_BR

### PR DESCRIPTION
**Pull request by Andrey-Matos**

### CODE REVIEW

**Comment by dimdenGD** [comment]
Words for this button should be short to fit in places, are you sure old translation was incorrect?

**Comment by Andrey-Matos** [comment]
Yes, unfortunately.
"Desseguidor" is not a real word in portuguese.

**Comment by dimdenGD** [comment]
image
seems that official Twitter uses this

**Comment by Andrey-Matos** [comment]
yeah, that would also work

**Comment by dimdenGD** [comment]
can you update file

**Comment by Andrey-Matos** [comment]
sure

**Pull request merged**
