### PR TITLE
add twitter blue rich text support (and fix a few things)

### PR DESCRIPTION
**Pull request by whakama**
this pr adds rich text support for twitter blue tweets, fixes poll options sometimes showing out of order, fixes quote tweets being treated as the tweet they quoted (i have no idea how else to describe it), and fixes some random overcomplications

rich text is just treated as an entity by parseNoteTweet (rich text works on non note tweets btw), then renderTweetBodyHTML parses the richtext "entity" with b and i html tags (just like it parses links but with bold tags and italic tags, basically)

to fix poll options, instead of taking the i from the loop for the arbitrary choice keys (for some reason, this sometimes ends up out of order?), it just takes only the number from the key and uses that as the "id"

parseNoteTweet now takes t as input instead (because its harder to add new stuff with arbitrary limitations like only being able to supply text and entities), which i also used to fix the quote tweet issue
and parseNoteTweets code now reads better

### CODE REVIEW

**Comment by dimdenGD** [comment]
Broke viewing tweets
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'hashtags')
    at renderTweetBodyHTML (helpers.js:478:22)
    at TweetViewer.appendTweet (tweetviewer.js:916:255)
    at async TweetViewer.updateReplies (tweetviewer.js:223:33)
```

**Comment by whakama** [comment]
i cant reproduce it exactly, what tweet is it on? i didnt write the hashtags part, but i definitely broke something with it that i didnt notice before and i did fix that, but id like to check if it also fixes this

**Comment by dimdenGD** [comment]
I can't find the tweet it happened on already..

**Comment by whakama** [comment]
i tested it a bit and used twitter while clicking every tweet for like 10 minutes and had no issues, i think the problem may have arised from me misreading a piece of code as the same as another piece and considering it redundant and removing it (the fix i talked about earlier), so i guess ill submit a pr for that and hope that really was the problem

**Pull request merged**
