### PR TITLE
zh_CN: sync translation

### PR DESCRIPTION
**Pull request by Yanstory**

### CODE REVIEW

**Comment by dimdenGD** [comment]
What's difference between this and https://github.com/dimdenGD/OldTwitter/pull/366

**Comment by Yanstory** [comment]
I optimized some formulation to make it more native.

Also I found some of translations by @lrisora are better than mines. Maybe I can have a review to make it better.

**Comment by dimdenGD** [comment]
Also please fix your file, google "JSON validator" and copypaste file into it and it'll show whats wrong with it

**Comment by Yanstory** [comment]
thanks, I copied the new strings and forgot add comma.

I followed some of lrisora's work and optimized it.

**Comment by dimdenGD** [comment]
Can you @Yanstory and @lrisora give me your Twitter profiles so I can properly credit you

**Comment by Yanstory** [comment]
Mine is `@carimowuling`

**Pull request merged**
