### PR TITLE
fix: layout jump on modal open

### PR DESCRIPTION
**Pull request by not-nullptr**
this pr (albeit hackily) fixes the annoying jump that occurs when you open a modal. haven't been able to test on firefox (i can't get the extension to install) but it should work

### CODE REVIEW

**Comment by dimdenGD** [comment]
what layout jump

**Comment by not-nullptr** [comment]
sorry, shouldve included an example. this PR is broken anyway, please bear with me while i fix it lol

https://github.com/user-attachments/assets/419f0886-70bf-46de-8842-d2e33d33db6c

**Comment by not-nullptr** [comment]
new commit seems to fix the issue entirely :)
https://github.com/user-attachments/assets/d6ae81e2-70c4-434a-add3-b5a3b96af069

**Comment by dimdenGD** [comment]
`fake-react-root` can be `react-root` if extension compatibility is enabled, so check for both

**Comment by not-nullptr** [comment]
small note - there's still a jump in the modal itself if the modal causes a scrollbar to appear, but for some reason nothing i try fixes it

**Pull request merged**
