### PR TITLE
Fix DM Sytle

### PR DESCRIPTION
**Pull request by Wintiger0222**
image
image
* DM UI fix

### CODE REVIEW

**Comment by Wintiger0222** [comment]
* Fixed 2 (CSS Problem)
* I think the screenshot referred to 1 on the Internet is wrong. I modified it.
image
3, 4 found and reproduced screenshots of real Twitter on the Internet.
Is it better to roll back?

**Comment by dimdenGD** [comment]
image
See how messages get grouped on screenshot when they're sent quickly, I think it would be good if there was thing like that

**Comment by Wintiger0222** [comment]
image
I tried to make it as similar as possible.

**Comment by dimdenGD** [comment]
Great, thanks

**Pull request merged**
