### PR TITLE
fix: remove old style suspension setting

### PR DESCRIPTION
**Pull request by not-nullptr**
sorry - last PR includes an old setting for a more accurate suspension page. this removes the broken setting

### CODE REVIEW

**Comment by not-nullptr** [comment]
new commits fix the `npm run build` command by using `archiver` instead of `adm-zip` :3c

**Comment by not-nullptr** [comment]
sorry - trying to get a branch back to the latest commit on this repo

**Comment by dimdenGD** [comment]
there's nothing broken with npm run build

**Comment by not-nullptr** [comment]
with `adm-zip`, the outputted files are corrupted and won't install in either chrome or firefox. i've been manually zipping the temporary folders to get the build working - `archiver` seems to actually work

**Comment by not-nullptr** [comment]
[OldTwitterFirefox.zip](https://github.com/user-attachments/files/16238654/OldTwitterFirefox.zip)
here's an artifact produced by `npm run build-action` on the latest commit in this repo. trying to install it will result in an error that it's corrupt, and trying to unzip it using 7-zip shows signs of the zip being corrupted:
image

**Comment by dimdenGD** [comment]
cant reproduce, unpacks fine for me

**Comment by not-nullptr** [comment]
maybe its a node version thing or something? i'm on v20.15.0

**Comment by dimdenGD** [comment]
how is node version related to unpacking a file

**Comment by not-nullptr** [comment]
node version is related to packing the file, not unpacking. modules can break depending on the version you're running - there's clearly some cause of it breaking on my machine

**Comment by dimdenGD** [comment]
you were talking about artifact not local build

**Comment by not-nullptr** [comment]
oh shit sorry i meant local build. my bad

**Comment by not-nullptr** [comment]
anything on this?

**Comment by dimdenGD** [comment]
i don't want to switch zipper

**Comment by not-nullptr** [comment]
does the new one not work on your system or something?

**Comment by dimdenGD** [comment]
i just dont rly trust it and lazy to test if it'll work without bugs

**Pull request closed without merging**
