### PR TITLE
Fix various mistakes in FR locale and add new locale lines

### PR DESCRIPTION
**Pull request by zdimension**
Some localizations were unnatural and used unusual translations for common Twitter things

### CODE REVIEW

**Comment by aur-c** [comment]
i understand why these changes were thought about, but except for typos and grammatical errors, i think most of them are subjective and useless

i agree to bytes being changed to their french equivalent octet, but i think things like capitalising english words, adding a space for question and exclamation marks, removing the accent of émoji even if the french word has one, and replacing some expressions with others even if they mean the same thing are only personal preferences

**Comment by zdimension** [comment]
> i understand why these changes were thought about, but except for typos and some wording, i think most of them are subjective and useless
> 
> i agree to bytes being changed to their french equivalent octet, but i think things like capitalising english words, adding a space for question and exclamation marks, removing the accent of émoji even if the French word has one, and replacing some expressions with others even if they mean the same thing are only personal preferences

Okay, sorry in advance this is gonna be a bit long ([Brandolini's law](https://en.wikipedia.org/wiki/Brandolini%27s_law)).

Most of my changes consisted of using what the regular Twitter UI uses, e.g.

- _compte_ instead of _utilisateur_
- _Tweet_ instead of _tweet_ (and _Retweet_, etc)
- strings for the advanced search dialog
- _afficher/masquer_ instead of _montrer/cacher_

Now, about the casing of _tweet_ and its friends, I checked Ngrams to see the usage trends, and it indeed seems that the lowercase form is [more prevalent](https://books.google.com/ngrams/graph?content=tweet%2C+Tweet&year_start=1995&year_end=2019&corpus=fr-2019&smoothing=3) in the French corpus (and as such disagrees with the Twitter way), so I agree that this part is debatable.

"_Compte_ Twitter" is simply [largely more common](https://books.google.com/ngrams/graph?content=compte+twitter%2C+utilisateur+twitter&year_start=1995&year_end=2019&corpus=fr-2019&smoothing=3&case_insensitive=true) than "_Utilisateur_".

_Afficher/masquer_ are, to me as a developer accustomed to designing and localizing GUIs, more natural-sounding translations than _montrer/cacher_ for _show/hide_. "_Montrer/cacher_" sounds weird to my ears the same way, say, "_Sauver_" sounds when used as a translation for "save" (and sadly I often see it in localizations of desktop apps, instead of just "_Sauvegarder_" or "_Enregistrer"_). One may call that personal preference, but I see it more as a consistency issue. I expect the same action to be called the same way in all apps I use, imagine if some app started translating "website" into "_site de la toile_", it's technically correct but it's not what the user expects. From an HMI point of view it reduces usability because it hampers the user's "linguistic muscle memory" 

The space before punctuation marks is just a standard and "normal" typography rule, not sure why you call this subjective. Of course I often omit the space when writing informal language but since this is the localization of an app we're talking about I think more formal language is expected.

The accent on _émoji_ is an oversight on my part. The official (as in, dictionary) spelling uses one, and usage seems to be [mixed](https://books.google.com/ngrams/graph?content=emoji%2C%C3%A9moji&year_start=2005&year_end=2019&corpus=fr-2019&smoothing=3) on the subject. I'll add the accents back when I get on my computer.

Note that in all of this comment, except when specified otherwise, I consider what is "normal" in the sense of "what the average speaker would expect". Hence my use of Ngrams, instead of, say, the Larousse or French Academy websites. Old people sitting in a room publishing a book every odd century is no basis for a system of determining the best way to write something. Ngrams follows popular usage, which to me is the closest we can get to the true usage of a word.

All in all, this is not a "filler commit" just to change things for the sake of changing them and getting my name on the contributors list. I spent time researching usage for words (except for emoji, I forgot) and making sure strings fit the width of elements and matched the punctuation of the corresponding English strings, so that the UI for the nice extension–I happen to also be a user of–can be nicer. 

Also, just to be clear, me changing a few strings in a JSON file is not a personal attack against you, nor would me changing a bit of code in any other GitHub repository be an attack against whomever changed that bit of code last. I'm sorry for making you feel that way, it was never my intention.

**Comment by aur-c** [comment]
oh no don't worry i wasn't offended at all

**Comment by aur-c** [comment]
i noticed two errors also, créée is not incorrect because it's accorded to extension, and chronologique inversée is not correct bc you don't accord inversé to an adjective

**Comment by zdimension** [comment]
> i noticed two errors also, créée is not incorrect because it's accorded to extension, and chronologique inversée is not correct bc you don't accord inversé to an adjective

Wait, I'm confused. The setting is called "chronologie" so I understood the values as accorded to chronologie. Like, "chronologie algorithmique", "chronologie chronologique inversée". Here what would algorithmique or chronologique be accorded to otherwise?

For créé, I wanted to accord it like "Traduit" next to it. But I agree it would make more sense as créée. But then shouldn't "translated" be "traduite"?

**Comment by dimdenGD** [comment]
`    "emoji": { "message": "émoji" },`
This should be uppercase

**Comment by aur-c** [comment]
> > i noticed two errors also, créée is not incorrect because it's accorded to extension, and chronologique inversée is not correct bc you don't accord inversé to an adjective
> 
> Wait, I'm confused. The setting is called "chronologie" so I understood the values as accorded to chronologie. Like, "chronologie algorithmique", "chronologie chronologique inversée". Here what would algorithmique or chronologique be accorded to otherwise?
> 
> For créé, I wanted to accord it like "Traduit" next to it. But I agree it would make more sense as créée. But then shouldn't "translated" be "traduite"?

at the time i did it very naturally, i thought about extension being créée and texte being traduit, but i see why you changed it now

for chronologique inversé, i think i thought about ordre and not chronologie, probably because it was accorded with ordre somewhere else

**Comment by zdimension** [comment]
Okay, makes sense, I see now it's "Type de chronologie". I'll put it in masculine.

And I'll put "traduit" in feminine so both are in same gender. Then I'll think the pr can be merged

**Pull request merged**
