### PR TITLE
Update messages.json

### PR DESCRIPTION
**Pull request by kriterin**
Fixed grammar errors

By the way they/them thing doesn't technically exist in Hebrew so I have to use "/" to make it neutral

### CODE REVIEW

**Comment by kriterin** [comment]
Does Twitter have gender preferences to how to call you? If yes I need to entirely write more for female versions of the asking messages like "Are you sure to block X user?"

**Comment by dimdenGD** [comment]
just open new twitter and look how its written there idk

**Comment by kriterin** [comment]
> just open new twitter and look how its written there idk

Checked most of the stuff there, it usually uses male here, but I still think the translated ver is enough

**Comment by dimdenGD** [comment]
Now translate rest of the file

**Pull request merged**
