### PR TITLE
Improve CSS 3

### PR DESCRIPTION
**Pull request by Wintiger0222**
* Fix width in CSS (for standardize each page)
* Show about when right-cell is hidden and left-cell is showing
* Korean Translation
* Remove Profile navibar margin (what is it for?)

### CODE REVIEW

**Comment by Wintiger0222** [comment]
(Add)
* Support Round button
Twitter has applied the current round button design to the legacy UI before the end of the service of the legacy UI. I think it's around 2019.
7-Twitter-Google-Chrome-2019-02-01-17 10 16-1024x837

**Comment by dimdenGD** [comment]
You should unify these settings into 1 setting called "Use 2019 Twitter design", also should make navbar buttons bold too

**Comment by dimdenGD** [comment]
And modernize `.box`

**Comment by Wintiger0222** [comment]
Can I shorten it to two types: new symbol and 2019 UI?
The new symbol is pretty, so I want to use it separately.

**Comment by dimdenGD** [comment]
You probably should just use Custom CSS for this

**Comment by Wintiger0222** [comment]
image
Theres' also a separate setting for round profile, but I don't understand putting it together.
Anyway. As you mentioned I modified navbar and .box, and I added CSS to match the 2018 (or 2019 or late 2017 whatever) UI.
And now if you activate the 2018 UI option, it also automatically enabled New Symbol, so if you don't like this setting, you can easily hide it from html with hidden properties.

**Pull request merged**
