### PR TITLE
Fix DM and date format, Update Korean translation and ETC

### PR DESCRIPTION
**Pull request by Wintiger0222**
* Fix incorrect line breaks for images with narrow widths in DM.
* Modify date format;  some languages use YYYYMMDD, instead of MMDDYYYY.
Two translations were added and 12 translation fixed to all languages during fixing date display.
(Added)
* Fix some page title
* Add [Mobile] text for some mobile only setting.
* Revert DM new message box color
* Add 4-digit notation option for CJK
* Update Korean Translation
* Add menu Icon and change order  for Mobile UI
image
* Improve mobile UI profile a little.
Modify followers and followings to separate from the tweet-nav bar.
and tweet-nav now shows when scroll downed in Mobile UI
also, use shorter message for narrow Mobile UI
image
* Add liked -> favorited translation

### CODE REVIEW

**Comment by dimdenGD** [comment]
I don't like profile changes

**Comment by Wintiger0222** [comment]
image
The separation of following and followers count from navbar, referred to the UI of the official app in 2015. This only applied on Mobile(width<590)
For the narrow UI, it looks better to separate the following/follower count than to separate the 
 tweet count.
 Making navbar invisible at the top of the profile page in mobile also referenced the official app. If you make it visible from the top, the page looks too stuffy.
If you don't like it, shall I revert everything on profile page.

**Comment by dimdenGD** [comment]
Can you at least style X FOLLOWING, X FOLLOWERS how it was in old app, also maybe we should change background color from gray to white then too

**Comment by Wintiger0222** [comment]
image
image
image

Modified to uppercase letters in the 2015 UI. And changed background to white. (Custom profile CSS still works fine)
Hides profile picture of 'follower you know' in Mobile UI and show user navbar a little earlier(be seen when the banner is almost up.)

**Pull request merged**
