### PR TITLE
Draft: Tweet rendering refactor

### PR DESCRIPTION
**Pull request by aloneunix**
### Summary:
Fixes:
- Hashtags that aren't rendered properly
- Hashtags that aren't hashtags

Adds:
- Hashflags to tweets
- Links for long tweets
- Hashtags (and hashflags) for long tweets

Bugs:
- Nicknames in replies on home timeline are stripped (due to `display_text_range`), so reply to an old tweet will appear as simple tweet (though it still would have a "Show thread" button). This looks weird in TL because `home_timeline.json` doesn't returns "conversations" as seen in `HomeLatestTimeline`.
- And some yet to discover.

### Description:
There are some issues with hashtags rendering due to using `hashtagRegex`, like hashtags that contain some characters that aren't in regex yet or rendering hashtags in places where there's no hashtag. 
Sure, we can add missing characters to said regex, but it would just grow constantly with every new character and won't fix a problem in the long term.
So to do this correctly I propose to use `indices` that are provided by backend for each entity, like hashtag, link, mention and so on.

This implementation is inspired by https://gist.github.com/LenaicTerrier/112880ee39723d182f71, but the difference is that it's not using substring or string iteration since that works on code points and breaks emojis, instead it converts whole string to array and iterates over it.

Also it doesn't use `<br>` for line breaks, instead it sets the "`white-space: pre-wrap;`" property (as seen in twitter itself).

2023-07-13_16-09-52_chrome

2023-07-13_16-16-25_chrome

What do you think?

### CODE REVIEW

**Comment by dimdenGD** [comment]
Sure, make sure to test this on every single page (Home, Profile, Tweet, List, Notifications, Bookmarks, TweetViewer)

**Comment by aloneunix** [comment]
Yeah, I'm planning to use it myself for at least a week before changing it from draft to "ready for review".

**Comment by aloneunix** [comment]
So, to address the issue of abandoned replies in timeline (due to nickname stripping from `display_text_range`) I've added the "replying to" element under the tweet header as seen in the mobile version.
diff

Does this idea looks okay?

**Comment by dimdenGD** [comment]
looks good

**Comment by dimdenGD** [comment]
I've been slowly moving all tweet-related CSS to header/style.css every time I edit something, you should add it to that file too instead of every single one

**Comment by aloneunix** [comment]
Is there any particular reason for `.emoji` to have `vertical-align: bottom` by default?
This is how it looks in nicknames on v1.7.4:
2023-07-22_00-02-55_chrome
I'm thinking of changing it to `text-top`

**Comment by dimdenGD** [comment]
it depends where emoji is located, it looks better on tweets this way i think
most of css values is just me testing and seeing whats best but .emoji is used in lot of places so might've not noticed it looks bad in particular places

**Comment by aloneunix** [comment]
So I went and checked every call of `twemoji.parse()`, the one that spawns `.emoji` - on some elements the difference is very subtle, about 1-2 pixels, but on the other ones it's a bit more apparent.

Comparison (left: `text-top`, right: `bottom`):

`appendUser`
appendUser

`circleSearch`
circleSearch

`location`
location

`newTweetUserSearch`
newTweetUserSearch

`notificationDiv`
notificationDiv

`profile-bio`
profile-bio

`renderDiscovery`
renderDiscovery

`renderTrends`
renderTrends
It's incredibly hard to find a trend with emoji, so I inserted one myself.
Also I added `text-decoration: underline` to some screenshots for demonstration purposes.

`renderUserData`
renderUserData

`shamelessPlug`
shamelessPlug


`tweet-body-text-long`
tweet-body-text-long

`user-preview`
user-preview

Notes:
- Skipped DMs because `.message-element .emoji` is already set to `middle` and looks OK
- Skipped `circleMembers` and `listMembers` because on screenshots there weren't any difference
I also noticed that twemoji aren't rendered in profile page on `#user-name`.

So after checking all these places I assume it's perfectly safe to change this property to `text-top` globally.

**Comment by dimdenGD** [comment]
Change it

**Pull request merged**
