### PR TITLE
Update Korean Translation and Add translation recommend text

### PR DESCRIPTION
**Pull request by Wintiger0222**
image

(Edited)
* Borrow the text from Old Twitter.
This text is recommendation for foreign language translation.

### CODE REVIEW

**Comment by Wintiger0222** [comment]
(Edit) Add Red Button

**Comment by Wintiger0222** [comment]
(Add)
* Fix Some trend shows undefined meta description

**Comment by Wintiger0222** [comment]
(Add) Fix when multiple user replied, only one user was shown

**Comment by dimdenGD** [comment]
All new translation lines must be added to bottom, do not insert anything on top or middle (Twitter)

**Comment by Wintiger0222** [comment]
(Edit) Moved text to the bottom
P.S I thought it was an important text, so I put it at the top as much as possible.

**Comment by Wintiger0222** [comment]
I need to see how to judge mentions and replies, so I'm going to changed it to draft

**Comment by Wintiger0222** [comment]
image
(fix) mentioned is not shown as replied user

**Comment by Wintiger0222** [comment]
(Add)
* Make save-search button moves to left when browser window is narrow/

**Pull request merged**
